function [q_N,q_NN,Q_N] = terminal_cost_quad(Q_t,x_goal,x_bar)
% Terminal cost expression
q_N = Q_t(1,1)*(x_bar(1)/2 - x_goal(1)/2)*(x_bar(1)-x_goal(1))+...
    Q_t(2,2)*(x_bar(2)/2-x_goal(2)/2)*(x_bar(2)-x_goal(2));
q_NN = [Q_t(1,1)*(x_bar(1)-x_goal(1))/2 + ...
     Q_t(1,1)*(x_bar(1)/2 - x_goal(1)/2),...
     Q_t(2,2)*(x_bar(2)-x_goal(2))/2 + Q_t(2,2)*...
     (x_bar(2)/2 - x_goal(2)/2)];
 q_NN = q_NN.';
 Q_N = Q_t;
end

